In [ ]:
import numpy as np
from convmodel import *

In [63]:

x = np.random.randn(3, 3, 2)
x.shape
x[1].shape

(3, 2)

In [92]:
print(x)
x[0:1]

[[[ 1.03991378 -2.05140623]
  [-0.047257   -0.40820527]
  [-0.2245728  -0.10828881]]

 [[-1.43031687  0.91579489]
  [ 0.31542427  0.35374166]
  [ 1.15098775  0.8177731 ]]

 [[ 1.10155775  0.81255051]
  [ 1.20707399  1.35421622]
  [ 1.0032933   1.14226284]]]


array([[[ 1.03991378, -2.05140623],
        [-0.047257  , -0.40820527],
        [-0.2245728 , -0.10828881]]])

In [93]:
hparameters = {"pad" : 1,
               "stride": 2}

stride = hparameters['stride']

stride

2